In [2]:
import os
import re
import pandas as pd
import json
import glob
import csv
import ast
import numpy as np
import pandas as pd
import openai
import random
import re
from flatten_json import flatten
from time import process_time
import ipywidgets as widgets
from IPython.display import display, clear_output
from retry import retry
from zhon.hanzi import punctuation
import pycorrector as pc
import pinyin_tone_converter as ptc
import warnings
warnings.filterwarnings("ignore")

In [3]:
import math
import pykakasi
import re
import string
from zhon.hanzi import punctuation
import random

In [142]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from scipy.linalg import norm
 
def tfidf_similarity(s1, s2):
    def add_space(s):
        return ' '.join(s)
     
    # Add space in between-words
    s1, s2 = add_space(s1), add_space(s2)
    # convert to TF Vector
    cv = TfidfVectorizer(tokenizer=lambda s: s.split())
    corpus = [s1, s2]
    vectors = cv.fit_transform(corpus).toarray()
    # Count TF Coefficent
    return np.dot(vectors[0], vectors[1]) / (norm(vectors[0]) * norm(vectors[1]))

In [143]:
from simhash import Simhash
def simhash_demo(text_a, text_b):
    """
    Get two texts' similarity
    :param text_a:
    :param text_b:
    :return:
    """
    a_simhash = Simhash(text_a)
    b_simhash = Simhash(text_b)
    max_hashbit = max(len(bin(a_simhash.value)), len(bin(b_simhash.value)))
    # Hamming Distance
    distince = a_simhash.distance(b_simhash)
    print(distince)
    similar = 1 - distince / max_hashbit
    return similar

In [19]:
df=pd.read_csv("Japanese_correction_datasets/jwtd/gen/jwtd_test_combined.csv")
df.head()

,page,pre_rev,post_rev,pre_loss,post_loss,post_text,diffs,pre_txt,post_txt,category,...,gpt35_romanji_gen,gpt35_incorrectstrings_gen,gpt35_romanji_time,gpt35_incorrectstrings_time,opennmt_model_textsim,gpt_35_romanji_textsim,gpt35_incorrectstrings_textsim,opennmt_model_simhash_textsim,gpt35_romanji_simhash_textsim,gpt35_incorrectstrings_simhash_textsim
0,881,5958209,9736989,251.51,245.60,1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,"[{'pre': 'を', 'post': 'の'}]",1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,substitution,...,0,1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,0,0.066108,1.0,0,0.983143,1.0,0,0.875000
1,887,31045825,31065369,189.78,175.93,制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,"[{'pre': 'か', 'post': 'も'}]",制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,substitution,...,0,制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,0,0.011402,1.0,0,0.982616,1.0,0,0.876923
2,1253,38176846,38227527,201.24,189.63,一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えられた集団...,"[{'pre': 'れれ', 'post': 'られ'}]",一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えれれた集団...,一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えれれた集団...,substitution,...,0,一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えられた集団...,0,0.011292,1.0,0,0.983214,1.0,0,0.892308
3,1253,35848754,35899590,98.14,94.01,フロント部に金色のプレートなど、随所に金色の装甲が発生している。,"[{'pre': 'に', 'post': 'の'}]",フロント部に金色のプレートなど、随所に金色に装甲が発生している。,フロント部に金色のプレートなど、随所に金色に装甲が発生している。,substitution,...,0,フロント部に金色のプレートなど、随所に金色の装甲が発生している。,0,0.009064,1.0,0,0.975900,1.0,0,0.772727
4,1432,67727119,68197779,528.34,521.10,このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,"[{'pre': 'もと', 'post': 'もの'}]",このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,substitution,...,0,このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,0,0.013184,1.0,0,0.997275,1.0,0,0.909091

In [121]:
import pykakasi

kks = pykakasi.kakasi()

def df_kana(df):
    
    df=df.assign(pre_romanji=0,post_romanji=0)
    

    for i in range(df.shape[0]):
        
        result = kks.convert(df.pre_txt.iloc[i])
        result1 = kks.convert(df.post_txt.iloc[i])
        lst=[]
        lst1=[]
        for item in result:
            lst.append(item['hepburn'])
        df.pre_romanji.iloc[i]=' '.join(lst)
        
        for item in result1:
            lst1.append(item['hepburn'])
        df.post_romanji.iloc[i]=' '.join(lst1)
            
            #print("{}: kana '{}', hiragana '{}', romaji: '{}'".format(item['orig'], item['kana'], item['hira'], item['hepburn']))

    return df

In [122]:
df=df_kana(df)

In [123]:
df.tail()

,page,pre_rev,post_rev,pre_loss,post_loss,post_txt,diffs,pre_txt,category,pre_romanji,...,gpt35_incorrectstrings_time,opennmt_model_textsim,gpt_35_romanji_textsim,gpt35_incorrectstrings_textsim,opennmt_model_simhash_textsim,gpt35_romanji_simhash_textsim,gpt35_incorrectstrings_simhash_textsim,pesedo_romanji,noise_num,pesedo_details
8537,3877588,71062937,71163561,213.38,206.69,ビザンツ帝国の支配は820年代の後半までに終わり、クレタ島はアンダルス（イベリア半島）からや...,"[{'pre': '広範', 'post': '後半'}]",ビザンツ帝国の支配は820年代の広範までに終わり、クレタ島はアンダルス（イベリア半島）からや...,kanji-conversion,bizantsu teikoku no shihai ha 820 nendai no ko...,...,0.0,0.966541,0,0.0,0.924242,0,0.0,bizantsu teikoku no shihai ha 820 nendai no ko...,0,[]
8538,3932005,72407958,72458531,44.27,46.42,乗り物や人混みが苦手。,"[{'pre': '人込み', 'post': '人混み'}]",乗り物や人込みが苦手。,kanji-conversion,norimono ya hitogomi ga nigate.,...,0.0,0.820021,0,0.0,0.742424,0,0.0,norimono ya hitogomi ga nigate.,1,"[{'origin_token': 'o', 'noise_token': '', 'noi..."
8539,3932005,72407958,72458531,58.89,62.67,れんげと同様人混みが苦手。,"[{'pre': '人込み', 'post': '人混み'}]",れんげと同様人込みが苦手。,kanji-conversion,rengeto douyou hitogomi ga nigate.,...,0.0,0.847762,0,0.0,0.742424,0,0.0,rengeto douyou hitogomi ga nigate.,0,[]
8540,3937616,72517512,72517518,476.97,476.58,権翼はなおも「陛下は小信を重んじ、社稷を軽んじられております。臣が見ます所、一度行かせれば二...,"[{'pre': '生かせれ', 'post': '行かせれ'}]",権翼はなおも「陛下は小信を重んじ、社稷を軽んじられております。臣が見ます所、一度生かせれば二...,kanji-conversion,kenyoku hanaomo( heika ha shou shin wo omon ji...,...,0.0,0.991141,0,0.0,0.878788,0,0.0,kenyoku hanaomo( heika ha shou shin wo omon ji...,2,"[{'origin_token': 'u', 'noise_token': 'u', 'no..."
8541,3947988,72805433,72807446,439.61,438.45,フォーブスの「アメリカで最も裕福なセレブリティ」（フォーブスのアメリカでもっともゆうふくなセ...,"[{'pre': '史', 'post': '誌'}]",フォーブスの「アメリカで最も裕福なセレブリティ」（フォーブスのアメリカでもっともゆうふくなセ...,kanji-conversion,foobusu no( amerika de mottomo yuufuku na sere...,...,0.0,0.994050,0,0.0,0.878788,0,0.0,foobusu no( amerika de mottomo yuufuku na sere...,0,[]

In [139]:
import math
import re
import numpy as np
import pandas as pd
import string
from zhon.hanzi import punctuation
import random




t26_keyboard = {'q': (0, 0), 'w': (0, 1), 'e': (0, 2), 'r': (0, 3), 't': (0, 4), 'y': (0, 5), 'u': (0, 6),
                    'i': (0, 7), 'o': (0, 8), 'p': (0, 9),
                    'a': (1, 0), 's': (1, 1), 'd': (1, 2), 'f': (1, 3), 'g': (1, 4), 'h': (1, 5), 'j': (1, 6),
                    'k': (1, 7), 'l': (1, 8),
                    'z': (2, 0), 'x': (2, 1), 'c': (2, 2), 'v': (2, 3), 'b': (2, 4), 'n': (2, 5), 'm': (2, 6)
                    }
t9_keyboard = {
      'a': (0, 1), 'b': (0, 1), 'c': (0, 1),
      'd': (0, 2), 'e': (0, 2), 'f': (0, 2),
      'g': (1, 0), 'h': (1, 0), 'i': (1, 0),
      'j': (1, 1), 'k': (1, 1), 'l': (1, 1),
      'm': (1, 2), 'n': (1, 2), 'o': (1, 2),
      'p': (2, 0), 'q': (2, 0), 'r': (2, 0), 's': (2, 0),
      't': (2, 1), 'u': (2, 1), 'v': (2, 1),
      'w': (2, 2), 'x': (2, 2), 'y': (2, 2), 'z': (2, 2)
  }




# Define a function to calculate the Euclidean distance between two points
def calculate_distance(point1, point2):
    x1, y1 = point1
    x2, y2 = point2
    return math.sqrt((x1 - x2)**2 + (y1 - y2)**2)

coordinates = list(t26_keyboard.values())



def fixed_strings(fstr): 
    E=ast.literal_eval(fstr)
    filtered_chars = []
    for item in E:
        pre_value = item['pre']
        if len(pre_value) >= 2:
            filtered_chars.append(pre_value[:2])
        else:
            filtered_chars.append(pre_value)
        
#filtered_chars=list(set(filtered_chars))
    kks = pykakasi.kakasi()
    s=[]
    for it in filtered_chars:
        result = kks.convert(it)
        for item in result:
            s.append(item['hepburn'])
    
    return s



def typo_romanji(fstr): 
    E=ast.literal_eval(fstr)
    filtered_chars1 = []
    filtered_chars2 = []
    for item in E:
        pre_value = item['pre']
        post_value = item['post']
        if len(pre_value) >= 2:
            filtered_chars1.append(pre_value[:2])
        else:
            filtered_chars1.append(pre_value)
            
        if len(post_value) >= 2:
            filtered_chars2.append(post_value[:2])
        else:
            filtered_chars2.append(post_value)
        
    filtered_chars1=list(set(filtered_chars1))
    filtered_chars2=list(set(filtered_chars2))
    kks = pykakasi.kakasi()
    pre=[]
    post=[]
    for it in filtered_chars1:
        result = kks.convert(it)
        for item in result:
            pre.append(item['hepburn'])
    
    for it in filtered_chars2:
        result = kks.convert(it)
        for item in result:
            post.append(item['hepburn'])
            
            
    return pre,post






punctuations = punctuation + string.punctuation + '1234567890・★ →'

def kanji_pesedo_build(valid_kanji,fixed_lst):

    valid_kanji_new=valid_kanji.lower()
    valid_kanji_new=' '.join(filter(lambda x: x not in punctuations, valid_kanji_new)).split()
    valid_kanji_new=[item for item in valid_kanji_new if item not in fixed_lst]

    #if random.random() <= 0.9:
        #error_num=random.randint(1, 2)
    #else:
        #error_num=0

    error_num=random.randint(0,2)
    noise_token=random.choices(valid_kanji_new,k=error_num)

    invalid_kanji=valid_kanji.split()
    valid_position=[]
    details=[]

    for item in noise_token:
        initials=' '.join(item).split()
        finals=initials
        kanji=str(item)

        error_type = random.choice(['missing', 'extra','typo'])
        if error_type == 'extra':
            position = random.randint(0, len(kanji))
            error = random.choice(initials + finals)
            kanji = kanji[:position] + error + kanji[position:]


        else:
            if error_type == 'missing':
                position = random.randint(0, len(kanji) - 1)
                kanji = kanji[:position] + kanji[position + 1:]

            else:
                p=random.random()
                if p < 0.6:
                    position = random.randint(0, len(kanji)-1)
                    reference_point = t26_keyboard[kanji[position]]
                    # Filter coordinates based on distance <= 1 from the reference point
                    filtered_coordinates = [coord for coord in coordinates if calculate_distance(reference_point, coord) == 1]
                    filtered_lst=[]
                    for ig in filtered_coordinates:
                        filtered_dict = [key for key, value in t26_keyboard.items() if value == ig ]
                        filtered_lst.append(filtered_dict[0])
                        noise=random.choice(filtered_lst)
                        kanji=list(kanji)
                        kanji[position]=noise
                        kanji=' '.join(kanji)
                else:
                    position = random.randint(0, len(kanji) - 1)
                    kanji=list(kanji)
                    kanji[position],kanji[position-1]=kanji[position-1],kanji[position]
                    kanji=' '.join(kanji)


        details.append({'origin_token': item, 'noise_token': kanji, 'noise_type':error_type})

        for index, value in enumerate(invalid_kanji): 
            if value == item:
                valid_position.append(index)
                invalid_kanji[index]=kanji
    invalid_kanji=' '.join(invalid_kanji)

    
    return {'invalid_kanji_gen':invalid_kanji, 'noise_num':error_num,'details':details }


if __name__ == '__main__':

    df=df.assign(pesedo_romanji=0, noise_num=0,pesedo_details=0)
    for i in range(df.shape[0]):
        if df.iloc[i].category!="kanji-conversion":
            df.pesedo_romanji.iloc[i]==df.iloc[i].pre_romanji
            details=[]
            details.append({'origin_token': ''.join(typo_romanji(df.diffs.iloc[i])[0]), 'noise_token': ''.join(typo_romanji(df.diffs.iloc[i])[1]), 'noise_type':df.category.iloc[i]})
            df.pesedo_details.iloc[i]=details
            df.noise_num.iloc[i]=df.iloc[i].pesedo_details.count("noise_token")

        else:    
            valid_kanji=df.pre_romanji.iloc[i]
            fixed_lst=fixed_strings(df.iloc[i].diffs)

            t=kanji_pesedo_build(valid_kanji,fixed_lst)
            df.pesedo_romanji.iloc[i]=t.get("invalid_kanji_gen")
            df.noise_num.iloc[i]=t.get("noise_num")
            df.pesedo_details.iloc[i]=t.get("details")

In [140]:
df

,page,pre_rev,post_rev,pre_loss,post_loss,post_txt,diffs,pre_txt,category,pre_romanji,...,gpt35_incorrectstrings_time,opennmt_model_textsim,gpt_35_romanji_textsim,gpt35_incorrectstrings_textsim,opennmt_model_simhash_textsim,gpt35_romanji_simhash_textsim,gpt35_incorrectstrings_simhash_textsim,pesedo_romanji,noise_num,pesedo_details
0,881,5958209,9736989,251.51,245.60,1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,"[{'pre': 'を', 'post': 'の'}]",1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,substitution,1987 nen ni kyokubu ginga gun ( dai mazeran ku...,...,0.066108,1.000000,0,0.983143,1.000000,0,0.875000,0,0,"[{'origin_token': 'wo', 'noise_token': 'no', '..."
1,887,31045825,31065369,189.78,175.93,制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,"[{'pre': 'か', 'post': 'も'}]",制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,substitution,"seiyaku ga ooku, dokusenteki ・ chouki ni rensa...",...,0.011402,1.000000,0,0.982616,1.000000,0,0.876923,0,0,"[{'origin_token': 'ka', 'noise_token': 'mo', '..."
2,1253,38176846,38227527,201.24,189.63,一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えられた集団...,"[{'pre': 'れれ', 'post': 'られ'}]",一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えれれた集団...,substitution,issetsu niha gurongi ni yabure ta hokano buzok...,...,0.011292,1.000000,0,0.983214,1.000000,0,0.892308,0,0,"[{'origin_token': 'rere', 'noise_token': 'rare..."
3,1253,35848754,35899590,98.14,94.01,フロント部に金色のプレートなど、随所に金色の装甲が発生している。,"[{'pre': 'に', 'post': 'の'}]",フロント部に金色のプレートなど、随所に金色に装甲が発生している。,substitution,"furonto bu ni kin'iro no pureeto nado, zuisho ...",...,0.009064,1.000000,0,0.975900,1.000000,0,0.772727,0,0,"[{'origin_token': 'ni', 'noise_token': 'no', '..."
4,1432,67727119,68197779,528.34,521.10,このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,"[{'pre': 'もと', 'post': 'もの'}]",このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,substitution,"konoyouna giron wo tsuuji, sukunakutomo roushi...",...,0.013184,1.000000,0,0.997275,1.000000,0,0.909091,0,0,"[{'origin_token': 'moto', 'noise_token': 'mono..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8537,3877588,71062937,71163561,213.38,206.69,ビザンツ帝国の支配は820年代の後半までに終わり、クレタ島はアンダルス（イベリア半島）からや...,"[{'pre': '広範', 'post': '後半'}]",ビザンツ帝国の支配は820年代の広範までに終わり、クレタ島はアンダルス（イベリア半島）からや...,kanji-conversion,bizantsu teikoku no shihai ha 820 nendai no ko...,...,0.000000,0.966541,0,0.000000,0.924242,0,0.000000,bizantsu teikoku no shihai ha 820 nendai no ko...,2,"[{'origin_token': 'i', 'noise_token': 'ii', 'n..."
8538,3932005,72407958,72458531,44.27,46.42,乗り物や人混みが苦手。,"[{'pre': '人込み', 'post': '人混み'}]",乗り物や人込みが苦手。,kanji-conversion,norimono ya hitogomi ga nigate.,...,0.000000,0.820021,0,0.000000,0.742424,0,0.000000,norimono ya hitogomi ga nigate.,0,[]
8539,3932005,72407958,72458531,58.89,62.67,れんげと同様人混みが苦手。,"[{'pre': '人込み', 'post': '人混み'}]",れんげと同様人込みが苦手。,kanji-conversion,rengeto douyou hitogomi ga nigate.,...,0.000000,0.847762,0,0.000000,0.742424,0,0.000000,rengeto douyou hitogomi ga nigate.,2,"[{'origin_token': 'o', 'noise_token': 'p', 'no..."
8540,3937616,72517512,72517518,476.97,476.58,権翼はなおも「陛下は小信を重んじ、社稷を軽んじられております。臣が見ます所、一度行かせれば二...,"[{'pre': '生かせれ', 'post': '行かせれ'}]",権翼はなおも「陛下は小信を重んじ、社稷を軽んじられております。臣が見ます所、一度生かせれば二...,kanji-conversion,kenyoku hanaomo( heika ha shou shin wo omon ji...,...,0.000000,0.991141,0,0.000000,0.878788,0,0.000000,kenyoku hanaomo( heika ha shou shin wo omon ji...,2,"[{'origin_token': 'o', 'noise_token': 'oo', 'n..."
8541,3947988,72805433,72807446,439.61,438.45,フォーブスの「アメリカで最も裕福なセレブリティ」（フォーブスのアメリカでもっともゆうふくなセ...,"[{'pre': '史', 'post': '誌'}]",フォーブスの「アメリカで最も裕福なセレブリティ」（フォーブスのアメリカでもっともゆうふくなセ...,kanji-conversion,foobusu no( amerika de mottomo yuufuku na sere...,...,0.000000,0.994050,0,0.000000,0.878788,0,0.000000,foobusu no( amerika de mottomo yuufuku na sere...,0,[]

In [144]:
df.columns

Index(['page', 'pre_rev', 'post_rev', 'pre_loss', 'post_loss', 'post_txt',
       'diffs', 'pre_txt', 'category', 'pre_romanji', 'post_romanji',
       'opennmt_model_gen', 'gpt35_romanji_gen', 'gpt35_incorrectstrings_gen',
       'gpt35_romanji_time', 'gpt35_incorrectstrings_time',
       'opennmt_model_textsim', 'gpt_35_romanji_textsim',
       'gpt35_incorrectstrings_textsim', 'opennmt_model_simhash_textsim',
       'gpt35_romanji_simhash_textsim',
       'gpt35_incorrectstrings_simhash_textsim', 'pesedo_romanji', 'noise_num',
       'pesedo_details'],
      dtype='object')

In [145]:
# Test

print(df.loc[2].pre_txt)
#print(df.loc[2].post_txt)
print(df.loc[2].post_txt)

df.loc[4].pre_romanji

df.loc[4].post_romanji

df.loc[4].diffs

df.loc[4].pesedo_details

,page,pre_rev,post_rev,pre_loss,post_loss,post_txt,diffs,pre_txt,category,pre_romanji,...,gpt35_incorrectstrings_time,opennmt_model_textsim,gpt_35_romanji_textsim,gpt35_incorrectstrings_textsim,opennmt_model_simhash_textsim,gpt35_romanji_simhash_textsim,gpt35_incorrectstrings_simhash_textsim,pesedo_romanji,noise_num,pesedo_details
2998,985570,18433991,18448517,191.50,183.11,「チューチューチュー」ならスーパーリーチ確定で、猫が登場してネズミを捕まえれば確変大当たり確定。,"[{'pre': 'が', 'post': ''}]",「チューチューチュー」ならスーパーリーチ確定で、猫が登場してがネズミを捕まえれば確変大当たり確定。,insertion,"( chuuchuuchuu )nara suupaariichi kakutei de, ...",...,0.0,0.995183,0,0.0,0.939394,0,0.0,0,0,"[{'origin_token': 'ga', 'noise_token': '', 'no..."
2999,985570,15304875,15304907,235.16,225.16,また、突入時の回転でリーチが掛かった場合は大当たり確定となり、突入時の回転で青以外の泥棒や大...,"[{'pre': 'と', 'post': ''}]",また、突入時の回転でリーチが掛かった場合はと大当たり確定となり、突入時の回転で青以外の泥棒や...,insertion,"mata, totsunyuu tokino kaiten de riichi ga kak...",...,0.0,0.996214,0,0.0,0.893939,0,0.0,0,0,"[{'origin_token': 'to', 'noise_token': '', 'no..."
3000,991318,67204287,67216756,232.02,223.92,土谷は両親、弟妹、生徒の親らの前で合田から「オウムをやめると言わなければ殺すど」、母親から「...,"[{'pre': 'た', 'post': ''}]",た土谷は両親、弟妹、生徒の親らの前で合田から「オウムをやめると言わなければ殺すど」、母親から...,insertion,"ta tsuchiya ha ryoushin, teimai, seito no oya ...",...,0.0,0.994104,0,0.0,0.892308,0,0.0,0,0,"[{'origin_token': 'ta', 'noise_token': '', 'no..."
3001,991318,66430056,66444069,149.48,133.93,あくまで「尊師の意思に従う。わたしから喋るわけにはいかない」というスタンスを貫いた。,"[{'pre': 'た', 'post': ''}]",あくまで「尊師の意思に従う。わたしから喋るわけにはいかない」というスタンスを貫いたた。,insertion,akumade( sonshi no ishi ni shitagau. watashika...,...,0.0,0.992994,0,0.0,0.921875,0,0.0,0,0,"[{'origin_token': 'ta', 'noise_token': '', 'no..."
3002,991318,66226316,66226392,257.99,248.97,村井秀夫や遠藤誠一の指示には非科学的なものも多く、二人の指示を聞いて失敗するべきなのかと麻原...,"[{'pre': 'の', 'post': ''}]",村井秀夫や遠藤誠一のの指示には非科学的なものも多く、二人の指示を聞いて失敗するべきなのかと麻...,insertion,murai hideo ya endou seiichi nono shiji niha h...,...,0.0,0.996855,0,0.0,0.969231,0,0.0,0,0,"[{'origin_token': 'no', 'noise_token': '', 'no..."
3003,991318,70158721,70158982,358.48,347.53,「実の兄のような気持ちを持っていた」などという大ウソをつきながら青山さんを検察・警察に売り渡...,"[{'pre': 'は', 'post': ''}]",「実の兄のような気持ちを持っていた」などという大ウソをつきながら青山さんをは検察・警察に売り...,insertion,( mi no ani noyouna kimochi wo motsu teita)nad...,...,0.0,0.998200,0,0.0,0.924242,0,0.0,0,0,"[{'origin_token': 'ha', 'noise_token': '', 'no..."
3004,991318,66489417,66495121,166.10,155.00,9月に入り、水戸支部長の岐部哲也から出家を促されるが家族と縁を絶てずに断った。,"[{'pre': 'い', 'post': ''}]",9月に入り、水戸支部長の岐部哲也から出家を促されるが家族と縁を絶てずにい断った。,insertion,"9 gatsu ni iri, mito shibuchou no kibe tetsuya...",...,0.0,0.978749,0,0.0,0.892308,0,0.0,0,0,"[{'origin_token': 'i', 'noise_token': '', 'noi..."
3005,991318,66409391,66409870,357.82,348.57,地下鉄サリン事件直前の3月20日未明、大阪道場に警察の強制捜査が入ったことを知り、クシティガ...,"[{'pre': 'で', 'post': ''}]",地下鉄サリン事件直前の3月20日未明、大阪道場に警察の強制捜査が入ったことを知り、クシティガ...,insertion,chikatetsu sarin jiken chokuzen no 3 gatsu 20 ...,...,0.0,0.996639,0,0.0,0.909091,0,0.0,0,0,"[{'origin_token': 'de', 'noise_token': '', 'no..."

In [147]:
dff=df.copy()

In [148]:
def textsim_opennmt_corrector(df):
    
    #for i in range(df.shape[0]):
        #if type(df.opennmt_model_gen.iloc[i]) == int:
            #df.opennmt_model_gen.iloc[i]=  str(df.opennmt_model_gen.iloc[i])


    
    for i in range(df.shape[0]):
        gen_text=''.join(filter(lambda x: x not in punctuation, df.opennmt_model_gen.iloc[i])) 
        org_text=''.join(filter(lambda x: x not in punctuation, df.post_txt.iloc[i]))
        if gen_text == org_text:
            df.opennmt_model_textsim.iloc[i]=1
            df.opennmt_model_simhash_textsim.iloc[i]=1

        else:
            
            df.opennmt_model_simhash_textsim.iloc[i]=simhash_demo(gen_text,org_text)
            
            df.opennmt_model_textsim.iloc[i]=tfidf_similarity(gen_text,org_text)
    
    return df

In [149]:
df=textsim_opennmt_corrector(df)
df.head()

8
7
7
15
6
12
7
6
6
10
12
14
12
6
10
7
7
4
4
13
10
12
4
10
9
14
7
3
4
9
1
3
19
17
7
5
3
10
1
7
5
19
13
11
8
6
6
3
3
7
6
7
7
5
6
5
11
26
7
13
10
15
5
4
8
9
9
10
3
6
16
3
13
5
7
7
9
17
8
5
8
11
8
7
13
11
7
16
11
9
3
8
15
7
6
8
3
6
5
13
6
13
4
8
10
7
10
4
12
2
4
11
6
6
0
6
5
6
17
13
7
3
9
3
3
4
5
7
4
18
10
9
4
9
9
10
8
6
6
16
2
14
10
4
14
6
8
15
13
5
8
5
9
9
7
5
6
12
6
6
17
7
1
8
9
20
8
5
20
8
7
12
4
5
10
8
1
3
8
6
7
10
6
7
6
4
8
7
10
5
17
6
10
16
2
15
5
5
6
11
4
12
5
9
5
7
8
16
9
11
5
3
6
11
6
2
4
3
10
9
8
6
8
6
5
10
6
3
9
9
13
15
8
7
7
3
10
7
5
4
3
10
9
6
8
6
8
7
7
6
8
5
3
3
7
9
4
6
11
2
13
6
4
9
11
13
18
11
6
9
4
14
13
11
10
6
10
5
10
13
7
7
4
8
6
6
5
13
5
5
4
14
5
5
9
15
5
9
2
6
8
6
3
8
5
6
11
6
17
13
11
8
3
9
7
19
11
7
6
21
4
9
10
6
6
4
6
6
15
3
15
9
10
15
5
16
2
8
9
5
5
7
7
5
5
5
13
11
6
5
9
10
11
5
4
10
26
4
8
8
8
10
12
12
9
4
5
8
4
7
5
11
21
10
7
10
8
2
8
15
13
4
6
5
5
3
9
9
5
7
11
6
7
6
6
5
7
12
4
15
2
13
16
4
6
11
4
13
11
10
9
6
9
14
9
13
9
5
8
9
8
14
8
9
10
9
13
7
8
15
15
2
10
5
7
5
7
4
6
4
2
11
12
12
10
8
13
13
5
7
6
2
7
11
11
5
9
6
4
10
10
9
10
18
14
23
5
6
3
8
6
9
8
4
3
8
15
4
10
12
7
12
3
8
7
12
8
6
5
5
14
4
9
8
9
15
8
8
8
6
5
10
11
12
14
0
6
5
5
6
11
10
9
5
4
9
15
2
5
8
11
17
7
7
8
10
12
7
6
3
8
10
4
8
12
8
6
6
2
16
11
8
6
4
7
7
12
3
9
17
4
13
9
10
7
6
4
3
7
5
3
14
8
7
3
10
6
6
9
6
8
4
5
5
7
6
6
8
15
3
8
2
11
17
5
11
11
6
6
10
11
7
14
7
9
6
14
5
17
6
8
1
10
8
6
8
8
6
10
3
6
18
7
10
7
7
6
10
10
7
3
7
5
4
8
6
8
11
6
8
2
4
1
7
11
9
7
10
5
5
8
10
9
10
2
10
9
1
9
10
3
5
4
9
11
4
10
20
14
2
6
6
3
5
6
5
22
8
16
6
10
11
4
1
9
7
8
6
4
5
11
6
12
4
10
16
12
11
2
6
10
11
6
2
5
5
12
7
6
8
12
4
5
2
9
2
4
4
13
13
5
12
9
6
9
7
15
6
11
9
9
25
15
4
3
16
17
6
6
11
12
5
8
8
8
9
13
9
4
8
9
5
22
8
11
14
5
5
12
7
4
6
6
18
5
1
6
17
6
5
7
2
6
11
4
8
9
18
11
13
10
2
5
4
2
11
16
6
3
4
4
16
13
9
7
6
12
6
8
6
8
10
12
10
10
15
5
7
9
11
16
7
11
8
1
8
9
8
8
8
10
6
5
8
4
11
13
13
13
8
6
13
11
8
6
5
7
9
6
5
7
9
11
11
15
12
5
9
8
5
10
5
8
7
8
11
23
7
12
13
11
17
6
7
10
12
4
9
14
7
4
7
11
10
4
3
6
4
11
6
7
3
11
11
3
11
12
7
9
3
8
9
8
5
10
15
5
9
15
7
23
8
11
6
7
7
3
5
3
5
6
6
7
8
3
6
6
9
3
15
7
7
13
10
3
6
8
3
3
6
5
8
8
6
3
11
7
14
6
7
9
7
8
6
8
11
11
6
16
7
7
7
9
13
8
7
6
5
8
6
8
10
4
9
3
6
10
8
6
11
4
7
10
15
7
5
13
7
5
16
8
8
1
3
14
15
8
9
16
11
10
17
5
7
8
9
8
8
5
7
10
2
3
9
7
5
4
8
8
11
6
11
8
2
4
9
9
2
6
7
10
7
9
10
9
14
9
5
18
11
9
2
3
7
8
6
6
3
8
9
5
10
7
7
6
5
8
7
7
8
10
1
2
8
8
5
18
15
12
11
11
11
10
4
9
1
11
2
19
10
13
7
13
5
3
3
6
16
5
6
9
6
7
3
7
4
6
12
6
8
9
13
4
5
5
7
12
15
16
6
10
9
9
23
8
8
12
8
14
7
7
7
5
3
22
6
7
7
9
9
7
9
10
9
6
14
7
5
7
7
8
5
5
5
7
8
16
9
8
10
10
7
4
12
7
11
5
9
5
5
10
17
14
9
10
13
5
13
2
7
3
4
6
12
10
1
12
16
6
7
3
17
11
12
9
9
6
8
14
13
3
8
13
12
6
8
8
9
10
3
8
13
9
9
16
14
10
20
5
9
8
6
12
7
12
10
11
6
6
5
5
13
10
8
5
15
13
8
3
9
5
12
5
5
8
8
9
3
6
6
10
9
9
8
18
3
8
6
7
12
3
10
5
5
9
12
28
4
5
10
9
7
11
7
12
14
9
5
13
3
5
8
13
11
7
7
4
2
7
14
7
7
8
7
5
6
3
7
6
7
11
8
10
8
0
13
6
10
8
7
8
12
9
13
2
10
10
8
2
8
7
10
5
5
8
11
4
7
12
2
4
5
7
9
12
7
27
11
4
4
4
4
10
15
7
4
18
8
17
12
1
17
4
6
8
6
7
12
8
8
12
6
7
3
10
6
7
13
14
5
9
8
8
19
9
5
4
7
8
8
7
11
6
11
6
6
15
9
9
19
16
12
8
6
19
9
8
11
5
13
2
6
3
10
8
6
4
13
6
11
25
20
15
11
14
14
24
8
11
6
8
6
16
8
6
8
6
4
13
6
8
10
7
9
15
1
10
3
13
17
16
12
11
17
6
8
4
4
9
9
7
9
15
5
5
9
13
8
6
7
6
13
9
10
5
14
9
7
12
7
4
7
7
3
9
15
3
10
6
3
7
10
7
9
14
9
10
13
4
6
9
10
6
4
7
7
8
10
5
6
12
1
7
10
8
5
10
6
10
14
9
9
18
8
12
9
10
6
13
3
15
6
13
5
6
3
6
12
10
6
17
4
4
9
9
7
7
6
13
7
13
10
6
8
6
8
4
16
7
4
8
11
14
9
11
10
4
10
9
13
7
8
19
15
13
9
8
8
7
4
8
10
3
5
5
13
7
12
5
2
9
14
8
10
7
13
7
9
7
11
9
10
4
5
5
5
14
9
3
5
8
7
8
9
3
18
10
27
11
8
13
14
8
13
12
4
7
6
8
11
2
9
11
10
8
4
9
9
9
2
11
4
4
3
12
13
7
4
8
7
7
9
10
7
4
15
6
9
11
1
12
11
16
6
7
11
9
8
9
9
9
1
16
5
5
11
8
5
8
7
15
10
16
11
9
1
11
3
8
13
4
12
14
3
8
8
6
5
5
8
5
5
8
6
14
9
6
15
15
5
5
8
5
6
8
9
6
12
8
14
17
10
4
11
14
7
11
8
8
3
7
6
5
9
6
12
3
12
7
9
4
2
9
11
7
5
5
6
6
7
13
8
9
9
8
22
11
11
8
10
20
6
7
3
6
4
8
12
9
11
11
2
16
6
4
3
10
3
5
1
5
7
8
7
7
5
3
2
6
9
6
7
5
4
17
12
9
7
6
5
7
10
5
15
10
8
11
10
5
17
6
10
7
3
5
7
10
5
5
10
8
19
4
4
9
15
5
14
2
6
12
11
8
10
7
3
8
5
5
5
6
10
10
16
5
6
5
4
6
7
9
7
13
5
6
8
2
12
5
2
5
11
5
4
9
11
11
5
5
6
4
11
0
3
11
16
3
4
12
9
6
6
9
6
4
5
15
8
1
4
8
14
2
2
2
15
6
8
7
9
3
8
12
0
11
6
6
8
5
11
8
4
7
12
5
6
5
6
4
0
2
5
9
1
13
7
2
4
5
12
10
6
6
8
4
8
4
9
8
8
7
9
2
14
7
8
7
3
8
20
9
5
2
2
5
11
16
11
8
8
9
9
8
9
17
3
10
0
4
6
6
7
3
4
5
11
6
12
6
6
11
4
8
8
3
3
3
11
2
5
11
11
5
6
9
10
6
11
15
8
9
11
3
11
6
9
7
7
8
5
11
2
14
13
11
10
12
7
4
5
7
10
6
9
11
3
13
6
12
9
8
23
7
7
16
5
3
9
10
5
5
15
5
6
10
7
0
6
3
4
9
4
6
7
6
10
12
1
6
4
3
7
9
8
12
7
7
5
4
13
4
4
7
10
7
26
4
4
6
9
5
9
4
9
5
8
4
1
8
11
5
3
2
5
5
11
3
6
2
5
7
8
5
4
14
11
9
5
4
5
5
11
10
5
5
1
8
5
11
8
10
9
2
6
5
8
6
12
7
9
9
14
8
11
4
5
14
7
7
8
5
14
4
8
4
7
5
6
7
4
5
4
16
4
5
14
10
11
3
8
12
14
9
10
11
6
3
4
8
9
7
14
4
11
5
9
9
9
6
4
9
9
10
7
4
11
10
5
10
7
11
4
16
5
6
10
15
10
4
2
6
6
4
8
5
2
4
7
3
3
6
2
15
7
7
9
8
7
3
8
6
9
3
4
1
3
5
10
4
13
5
8
9
10
13
5
13
5
7
4
11
7
13
6
5
4
8
2
3
14
8
6
11
7
1
11
8
3
8
13
4
7
11
13
9
4
6
9
7
4
4
14
5
11
7
5
7
5
4
3
3
5
11
11
9
7
6
7
10
4
5
15
8
7
14
9
7
11
9
6
5
13
10
9
7
13
9
10
8
10
4
8
4
7
11
6
5
12
5
8
5
10
11
5
5
6
1
7
11
7
9
12
15
6
6
13
9
4
1
8
8
10
9
4
12
6
6
4
2
9
14
7
10
23
7
4
11
4
8
7
4
10
3
12
14
19
4
14
6
7
9
2
2
10
12
10
3
6
7
11
9
7
7
5
3
8
8
5
8
8
7
11
8
4
6
7
4
6
4
8
12
2
6
8
15
9
4
14
7
4
5
3
11
14
2
6
6
7
5
22
2
7
1
11
8
3
2
4
13
12
19
7
11
8
8
9
15
8
10
1
9
11
8
8
5
12
6
2
6
6
10
2
7
9
10
7
5
4
7
9
11
5
10
5
5
7
9
8
1
5
13
16
8
15
8
2
5
3
6
5
9
3
7
7
12
7
5
7
15
9
10
3
5
11
10
9
1
8
1
13
17
6
15
13
8
10
7
12
7
17
9
6
13
11
6
17
5
5
16
14
12
3
9
5
12
9
2
8
11
13
15
7
0
14
9
9
7
8
2
7
13
14
6
9
8
8
6
4
7
5
15
9
6
9
6
3
7
15
5
17
6
4
12
10
25
3
21
9
16
5
9
1
10
7
5
2
3
3
8
7
3
6
2
10
4
13
11
19
8
8
14
3
13
11
4
5
6
14
9
4
12
8
5
10
4
7
3
6
2
5
2
5
12
9
10
2
6
11
5
6
9
4
2
5
8
11
14
7
9
5
4
5
5
9
4
16
10
5
11
18
7
10
10
7
7
13
2
6
13
8
5
9
8
19
9
2
5
9
13
8
4
10
2
7
4
2
12
4
9
10
8
11
8
4
12
11
7
8
4
10
9
9
10
10
5
11
16
1
2
12
5
16
7
9
10
6
6
6
8
10
3
5
10
5
8
14
8
11
7
5
13
9
9
3
6
7
3
18
14
7
3
7
9
4
10
3
2
3
8
5
17
7
5
8
6
16
5
3
7
2
4
8
9
6
8
3
7
25
7
5
5
7
10
7
2
15
7
9
4
7
13
7
4
11
6
5
6
3
8
3
12
12
7
4
10
13
13
5
5
10
3
8
5
11
7
5
8
8
4
8
10
6
2
11
5
22
9
7
6
10
3
10
6
9
5
5
20
7
15
8
8
8
11
10
12
5
4
5
6
13
5
0
6
6
13
8
11
8
13
13
7
6
5
4
9
12
9
3
5
4
11
7
13
3
5
6
3
2
5
12
6
5
11
11
17
8
9
5
13
6
13
7
6
9
9
2
6
6
10
11
10
4
9
8
5
5
5
6
20
7
14
8
10
3
4
6
9
7
10
3
6
6
10
9
11
8
13
9
8
2
11
2
11
10
14
6
3
8
4
7
5
6
8
8
9
8
6
2
4
4
5
10
8
13
8
10
11
8
2
2
4
3
11
11
8
6
6
9
8
19
17
8
7
11
10
9
5
4
4
6
3
4
12
15
20
9
2
20
15
7
13
9
10
1
5
8
5
3
11
9
6
14
12
5
13
7
4
9
5
9
12
7
4
12
9
11
6
6
10
11
4
5
14
8
6
8
12
6
5
4
9
5
19
10
6
8
3
5
5
4
7
4
12
4
11
6
8
13
7
4
4
16
10
5
7
10
6
5
7
5
8
7
10
5
12
19
10
4
7
7
5
2
5
7
6
5
7
7
6
2
6
8
14
6
15
4
7
12
12
11
15
6
5
10
7
12
2
5
14
7
4
2
9
12
8
6
7
7
8
12
7
19
8
11
4
6
6
7
20
11
5
6
6
7
10
6
7
12
11
6
3
7
13
7
4
8
5
7
9
12
5
14
2
6
2
6
5
11
4
8
4
5
9
11
11
7
11
6
19
11
7
6
12
10
5
9
9
14
11
10
8
6
12
10
6
9
11
7
8
7
14
21
5
8
11
6
5
13
7
5
9
16
6
12
6
4
10
4
9
2
7
7
8
8
6
9
2
8
2
13
16
10
20
7
7
7
7
13
10
4
4
12
18
5
6
9
12
3
6
12
4
10
7
10
8
10
13
12
7
2
0
9
8
8
21
7
10
3
10
10
2
5
14
4
15
11
2
3
7
6
4
11
3
5
9
9
12
5
7
5
6
4
11
11
10
8
10
2
3
11
5
5
11
11
5
9
10
9
6
6
4
15
15
3
6
5
1
8
4
6
4
8
9
3
15
6
11
6
14
5
5
6
11
11
16
4
1
4
8
12
7
7
2
7
6
8
6
8
15
6
9
8
7
2
18
6
6
7
5
8
4
7
7
8
8
11
25
8
5
7
3
9
7
11
11
7
3
9
3
3
5
7
8
9
3
4
7
22
24
5
9
4
6
9
13
6
8
5
10
5
11
14
5
6
8
5
7
4
3
12
5
13
7
8
7
13
9
1
8
9
6
6
8
9
14
15
2
7
9
5
6
8
3
9
5
14
8
11
7
9
6
6
6
9
3
10
9
2
5
16
19
5
6
8
7
2
4
8
6
5
2
13
7
4
10
10
11
11
6
12
6
7
5
6
8
6
10
8
15
2
3
8
11
4
6
9
13
3
4
5
2
18
12
10
6
4
7
10
5
8
6
15
10
13
10
5
4
5
5
5
9
7
12
7
7
1
7
8
9
2
7
14
8
4
11
4
5
5
8
9
5
5
5
4
4
3
7
0
10
8
3
8
6
10
13
11
6
3
4
5
10
3
10
7
6
11
7
7
8
3
6
21
1
6
7
2
11
16
6
5
5
8
14
12
3
23
11
4
4
5
2
4
10
13
8
2
6
6
5
8
4
10
6
8
11
7
8
9
16
4
7
8
8
8
3
6
7
9
9
6
5
9
3
1
5
10
3
9
4
7
7
8
8
10
5
1
7
5
12
9
6
6
6
12
9
2
5
4
5
10
22
7
8
5
6
5
5
8
9
14
2
9
11
3
3
9
5
5
9
2
6
10
21
5
7
11
15
7
12
5
3
9
15
7
8
5
9
16
4
12
6
4
3
9
12
3
10
9
3
13
12
8
5
7
6
5
11
6
9
7
8
6
7
8
10
13
7
4
2
5
10
6
6
12

6
7
13
7
6
8
4
7
11
1
11
5
6
17
13
4
10
10
5
6
12
13
3
12
16
8
8
7
4
8
6
9
10
9
13
10
7
12
3
5
4
16
17
11
5
8
4
9
7
2
2
5
8
5
6
2
8
9
10
5
8
9
4
12
9
9
6
5
3
16
9
6
7
2
7
7
10
8
6
4
2
7
4
12
5
9
5
9
5
4
5
11
6
5
4
10
5
5
4
8
20
12
15
9
7
10
5
5
10
6
5
7
8
4
8
7
7
11
6
4
7
4
5
9
9
2
11
12
11
2
6
6
5
3
4
4
12
13
5
3
8
4
7
7
2
11
12
12
5
5
11
7
2
10
14
7
6
8
7
6
11
6
7
4
21
6
4
9
1
8
3
9
14
10
18
7
5
5
11
4
5
16
7
1
4
11
16
2
5
5
7
9
18
8
8
8
13
5
3
8
8
7
9
13
8
5
11
8
9
6
11
7
6
9
11
9
5
3
11
7
4
3
28
4
9
11
7
9
5
8
5
7
3
16
4
13
10
4
7
8
9
8
11
13
13
7
1
11
5
7
3
6
29
6
5
10
3
9
6
4
9
10
3
6
9
12
2
4
12
7
4
10
9
8
5
9
5
10
9
14
5
4
4
5
16
2
11
7
8
4
8
12
13
25
20
3
10
10
9
9
8
10
2
5
16
4
11
7
4
8
5
11
18
5
11
11
8
10
17
8
7
6
5
4
4
13
5
5
7
9
18
17
22
7
12
6
9
7
4
6
4
9
14
6
8
6
5
9
3
9
11
6
7
8
10
8
3
9
4
13
4
6
3
7
10
9
2
11
6
2
7
6
6
7
7
8
10
26
8
11
9
7
4
6
10
8
4
11
12
5
12
2
4
2
4
7
12
8
12
15
4
10
14
10
9
8
5
6
10
6
7
10
6
8
9
4
3
6
5
8
7
7
5
9
8
13
11
12
8
10
8
7
10
9
6
9
8
10
8
2
4
8
12
24
14
5
4
7
1
8
16
15
14
6
4
3
7
4
6
13
8
6
4
8
8
7
6
5
8
7
8
9
7
8
20
12
9
3
10
15
7
9
10
4
7
9
11
9
6
7
8
1
22
3
6
7
8
3
4
15
6
9
10
7
12
4
2
7
7
8
9
9
9
3
13
9
6
12
16
14
7
27
15
8
9
5
6
5
5
5
10
4
13
7
18
9
5
7
8
6
7
5
8
10
6
6
8
3
5
5
8
5
4
4
4
8
6
13
9
19
8
6
6
18
5
11
6
6
11
5
4
10
11
14
13
4
2
11
13
12
13
5
6
7
4
3
7
19
7
10
7
9
9
7
5
12
9
6
6
8
8
11
4
5
7
17
7
10
9
9
11
5
11
9
6
5
9
4
8
3
10
3
5
7
11
9
8
11
5
3
6
1
9
10
16
11
15
7
5
6
8
6
6
4
9
10
6
13
6
9
9
9
4
7
6
3
12
13
17
5
13
8
6
12
4
9
4
8
3
6
6
20
10
9
7
6
9
9
4
5
5
3
3
3
9
4
5
6
4
5
24
25
12
9
3
8
5
9
3
11
5
8
25
11
6
10
5
4
5
14
8
10
9
5
8
6
4
3
17
3
1
7
5
9
5
6
8
5
4
9
3
4
12
8
7
7
30
5
3
6
6
12
7
11
8
7
17
9
10
10
20
10
4
9
3
7
3
14
7
8
11
9
6
17
5
2
8
16
12
8
4
6
7
6
7
7
9
16
10
8
7
4
7
10
10
7
9
6
6
14
3
7
7
3
3
6
11
6
25
6
7
8
10
3
8
5
5
9
6
4
5
7
9
8
8
5
31
5
13
32
2
5
4
5
9
12
6
18
6
6
4
5
19
9
7
11
3
10
10
9
9
4
5
7
4
5
15
11
11
11
13
9
6
6
6
6
6
23
21
13
0
12
9
22
24
7
3
3
9
2
10
3
8
11
8
8
11
7
6
13
9
5
9
8
7
6
9
3
10
10
1
5
8
2
3
6
6
4
11
16
4
5
6
6
3
9
6
14
1
4
9
8
10
25
11
13
5
6
7
7
13
14
14
9
9
6
4
6
18
8
4
12
10
13
3
9
4
12
5
13
7
4
8
11
12
8
12
9
6
15
15
7
11
4
9
6
6
3
3
14
3
5
7
10
0
8
2
8
7
6
9
9
8
8
4
10
6
6
15
4
12
4
10
11
5
4
13
7
9
20
13
10
4
9
7
9
10
12
8
8
12
10
17
8
10
8
7
8
9
7
2
3
9
10
8
9
2
12
7
10
14
12
7
8
6
9
15
9
5
10
7
5
4
11
4
3
17
11
10
8
13
4
8
13
5
9
6
2
7
7
4
17
6
3
7
5
17
8
7
9
10
9
7
9
5
10
8
4
11
5
17
4
3
9
8
7
4
10
4
2
6
3
18
11
10
7
12
12
14
12
14
14
7
5
16
10
6
13
4
4
4
6
11
9
3
8
10
17
1
9
7
7
6
8
7
7
6
12
5
6
8
5
5
8
4
5
10
7
11
7
6
9
8
4
11
5
11
10
5
8
26
7
7
17
14
6
2
4
30
10
7
5
7
5
12
5
7
5
5
5
14
13
11
14
15
4
9
17
7
8
14
6
8
14
12
6
3
6
4
7
8
7
3
12
8
9
6
3
25
35
12
8
9
4
8
9
8
6
5
2
15
7
10
7
5
5
8
8
11
23
11
5
5
4
11
20
4
8
11
8
5
4
14
8
3
3
7
5
6
5
3
6
4
8
11
5
6
8
10
13
6
6
5
8
10
19
15
10
7
10
13
2
14
6
9
9
17
15
9
2
6
12
6
6
9
6
12
7
7
2
4
8
13
9
10
10
8
17
3
8
9
12
25
6
8
10
7
5
11
6
7
4
7
18
10
8
3
15
12
15
5
5
4
5
9
6
8
12
12
10
12
9
12
6
4
17
8
9
12
8
3
7
7
20
9
5
13
7
6
9
11
8
6
10
15
5
8
11
12
6
9
9
18
20
8
7
6
13
10
12
12
9
7
4
16
8
4
13
5
8
7
9
6
8
4
5
7
5
7
7
9
10
12
11
9
5
6
8
14
5
9
2
15
4
10
7
9
9
11
5
11
4
9
7
10
6
11
8
14
9
8
10
8
5
5
6
2
12
4
21
11
10
7
12
15
10
14
5
10
7
4
4
29
14
9
7
16
9
4
7
8
5
4
14
8
13
4
10
12
7
7
11
7
4
7
7
12
7
10
10
25
14
6
9
6
5
4
9
5
7
10
4
4
1
7
7
27
11
10
7
10
4
5
12
9
8
11
15
16
4
9
11
16
10
7
5
10
5
14
7
4
3
4
4
8
4
12
6
12
16
2
8
14
11
7
9
10
4
11
6
7
3
11
24
6
3
5
14
15
4
7
18
9
14
5
11
14
4
7
10
5
2
5
26
12
7
1
9
3
6
9
9
6
8
6
17
11
4
4
23
15
7
4
7
8
13
8
9
10
10
7
4
12
11
6
8
28
5
4
5
10
4
7
7
8
10
5
10
7
11
14
6
13
7
10
4
10
8
10
7
8
7
0
6
6
5
9
6
5
8
9
7
7
5
5
5
13
6
10
8
13
14
10
10
5
8
4
8
11
6
10
5
10
10
2
7
4
6
6
12
8
4
4
14
8
2
9
4
12
8
6
5
11
7
6
6
6
7
11
5
8
8
2
5
5
5
14
8
7
9
10
5
7
9
5
5
4
10
9
8
9
19
4
8
4
4
5
12
6
10
3
7
7
5
23
14
8
4
5
2
6
10
26
10
11
18
7
6
4
5
10
12
11
2
5
9
12
6
7
8
7
10
5
12
9
5
7
8
5
4
2
7
10
15
14
11
5
16
13
11
3
4
9
5
6
4
15
6
9
15
8
8
7
5
6
5
9
32
11
9
12
7
8
6
2
17
13
11
7
12
4
6
7
7
13
10
8
12
4
16
6
8
10
11
3
7
7
8
12
6
9
5
5
11
10
3
3
5
11
5
4
15
6
7
4
10
7
8
4
3
12
8
9
24
9
10
10
18
8
4
5
6
11
5
7
23
6
4
7
10
11
8
4
6
6
10
8
12
7
9
6
13
17
8
6
5
5
6
5
7
7
9
14
6
4
8
12
9
8
9
5
14
13
7
3
11
9
13
13
6
12
7
8
5
13
13
9
14
18
19
6
12
12
15
9
7
7
9
9
7
8
7
8
2
8
5
2
6
5
5
3
10
5
9
7
9
6
8
4
20
4
5
5
7
6
3
6
9
8
5
12
8
1
15
4
10
6
8
6
7
9
6
7
14
10
7
8
7
2
5
5
4
7
18
11
4
8
9
6
10
5
10
10
4
5
4
5
11
6
5
9
7
12
6
3
2
9
12
2
3
6
8
5
8
6
14
6
8
3
8
13
4
8
19
8
7
6
6
11
14
3
7
16
9
2
8
11
8
13
12
12
13
3
12
10
8
8
9
8
8
7
7
6
7
9
9
10
6
4
11
3
9
11
15
5
5
4
12
7
10
9
8
9
8
8
2
3
5
6
5
3
4
7
7
8
6
9
3
13
9
16
10
14
8
9
6
6
6
11
13
8
2
4
5
9
6
7
4
17
6
14
24
8
8
3
12
12
7
8
19
5
6
13
8
9
8
8
10
5
15
6
8
5
9
8
6
3
5
4
9
8
2
10
10
6
7
6
8
9
7
8
8
5
8
10
9
8
5
10
13
10
9
12
2
9
8
5
13
13
9
9
3
9
4
18
20
15
4
5
8
8
10
3
8
7
18
11
11
16
3
7
7
12
9
12
14
7
5
11
6
13
7
15
12
3
7
8
9
14
6
5
8
8
11
9
4
9
4
11
12
7
8
6
7
10
6
14
6
5
5
6
17
13
19
11
16
17
11
15
13
6
13
16
6
4
5
12
17
14
4
16
11
8
9
11
4
7
9
10
12
12
20
5
7
4
12
5
8
7
8
9
7
19
13
6
16
9
8
2
8
6
19
6
11
11
6
2
3
8
7
19
2
16
3
10
3
10
6
7
9
5
8
5
13
17
3
4
7
8
13
9
6
4
6
8
7
10
7
8
7
13
4
12
4
4
4
5
5
14
6
17
7
9
13
5
6
13
13
10
10
6
12
7
11
8
6
9
5
10
7
16
9
11
11
7
5
6
5
6
10
15
8
9
9
7
7
4
10
11
10
6
8
5
6
3
3
3
7
11
9
9
3
8
24
8
9
9
8
4
14
14
14
5
7
8
5
10
9
4
16
7
10
6
6
21
7
21
11
10
5
4
6
4
11
5
13
7
5
9
12
13
2
5
4
9
5
17
13
5
20
13
16
8
6
8
11
4
10
17
9
7
6
12
14
11
5
10
6
11
5
6
12
23
8
12
1
10
6
8
7
12
5
9
6
18
11
8
4
8
7
14
6
5
8
18
6
17
11
10
11
6
12
4
11
8
8
8
7
15
10
6
7
13
4
5
11
8
9
9
10
12
12
16
9
5
8
10
6
7
8
5
12
10
11
12
7
14
13
5
7
2
5
8
6
11
6
12
18
11
10
12
9
19
12
4
8
2
4
7
4
6
14
8
2
11
6
13
7
5
4
9
7
14
6
5
8
6
7
8
9
5
8
24
7
12
10
5
14
4
20
11
3
13
4
17
21
9
9
6
10
7
10
6
9
8
8
16
5
6
5
11
9
13
11
10
15
9
2
4
3
5
10
12
6
9
12
9
7
6
9
7
6
14
12
9
4
6
11
8
14
9
9
6
11
12
3
8
6
7
12
7
9
13
12
6
10
6
8
9
6
4
12
11
5
6
7
7
11
5
9
4
6
4
12
11
3
12
7
6
6
9
5
12
2
5
5
7
9
10
6
3
13
7
5
12
6
3
8
11
5
12
10
9
4
8
5
2
12
6
9
3
7
6
13
8
6
10
8
7
7
11
8
5
6
8
5
11
6
7
9
4
15
10
10
7
6
11
1
3
4
7
11
7
4
8
3
19
7
4
5
4
8
23
10
13
8
8
5
8
3
10
21
3
7
6
9
5
17
7
7
5
8
10
9
7
3
11
6
9
1
7
12
3
5
8
4
5
12
9
8
10
10
10
10
11
13
6
11
13
19
1
11
5
5
9
7
11
8
9
10
3
12
12
8
14
16
8
13
19
8
8
11
5
14
9
6
11
10
8
8
8
7
15
10
6
7
10
9
7
9
10
2
4
5
6
4
23
6
16
10
12
7
10
7
6
4
11
8
6
6
7
12
16
11
9
17
6
12
6
8
11
3
3
8
7
3
3
7
1
5
3
13
14
8
4
19
11
19
8
4
3
9
1
10
8
5
6
7
9
9
8
10
15
13
8
17
13
11
2
8
9
6
12
7
7
9
2
7
13
11
11
7
8
18
10
9
14
8
8
12
9
7
4
10
5
8
14
9
11
15
19
3
11
7
8
7
8
2
2
9
10
7
7
7
6
9
8
5
14
15
4
14
9
6
20
8
1
10
4
10
6
7
15
9
12
12
12
14
4
8
3
9
9
10
8
6
5
10
8
4
6
10
5
9
9
15
6
4
5
7
7
8
5
9
10
8
19
9
10
5
1
6
6
17
6
3
7
4
9
8
10
8
11
7
7
13
16
7
8
26
10
5
9
6
2
8
7
6
5
20
11
18
18
2
11
5
9
10
5
5
10
10
5
9
8
17
14
9
15
15
13
9
12
2
12
9
7
12
7
4
11
3
8
2
11
13
6
5
7
11
11
14
7
8
17
15
9
2
7
7
15
9
4
12
6
7
7
11
10
13
15
4
7
10
25
3
11
9
6
12
6
6
7
2
4
14
7
12
9
7
12
10
18
6
9
11
8
12
8
8
9
6
7
7
8
10
10
18
6
7
14
8
8
8
12
4
7
8
15
7
10
22
13
4
14
7
3
9
19
19
7
9
19
10
8
8
2
4
13
3
5
11
7
13
8
10
4
9
5
7
6
10
8
11
6
17
10
8
2
11
7
5
9
2
7
7
8
16
8
10
7
7
9
1
5
9
5
5
7
12
12
6
6
2
8
21
8
10
5
7
4
12
6
5
14
9
14
14
5
12
2
11
8
7
6
16
5
12
8
14
5
7
5
5
7
5
5
8
11
9
8
20
6
9
9
6
15
6
13
9
7
7
0
7
10
16
6
9
7
5
13
1
12
10
4
8
8
18
10
13
15
6
12
7
7
19
8
6
6
6
8
6
6
4
4
0
10
4
11
1
4
8
3
6
10
11
7
7
9
11
11
6
8
6
11
10
19
5
12
10
10
11
7
9
12
7
8
9
3
5
16
15
3
4
10
4
8
2
17
8
5
8
9
10
8
6
7
3
17
15
15
12
5
7
8
15
11
9
11
8
6
10
2
9
17
7
11
5
5
6
2
12
17
7
3
6
8
10
19
8
6
6
8
12
6
6
7
22
8
10
8
4
5
5
13
7
13
11
8
4
8
14
9
10
15
14
5
8
15
10
5
16
8
7
11
8
14
13
16
9
9
13
9
11
13
8
11
8
6
7
14
8
7
14
16
4
9
3
15
13
14
5
9
8
6
10
8
11
16
11
7
2
19
9
7
3
9
9
10
7
7
2
10
9
7
21
5
7
11
13
9
11
3
11
9
5
15
8
11
5
7
23
17
6
14
5
12
16
8
6
11
9
11
8
7
9
8
6
5
0
7
12
10
8
7
8
7
9
9
5
5
5
12
10
10
9
10
7
10
10
7
4
9
3
16
8
3
9
6
19
6
12
10
8
6
6
11
20
14
10
17
5
12
14
8
11
10
16
18
15
10
4
6
10
7
7
10
11
12
4
5
8
18
18
10
6
13
15
7
4
16
14
11
7
9
6
8
14
12
9
8
10
12
3
7
4
6
3
5
11
10
1
12
9
6
4
11
7
7
6
19
5
8
4
11
10
6
14
5
13
8
5
1
7
11
11
8
10
7
10
1
7
18
19
7
16
13
11
5
11
7
9
17
4
4
11
15
6
12

9
11
3
6
6
4
17
8
7
10
5
8
6
5
10
16
4
10
13
8
11
6
5
16
8
10
6
10
13
6
10
15
16
8
2
10
13
16
7
13
16
6
4
13
15
12
7
8
11
12
15
6
13
12
8
9
17
4
4
4
12
8
11
11
11
7
11
10
7
0
11
12
5
16
23
18
9
8
9
10
10
20
8
10
7
7
9
12
6
8
11
5
5
7
7
4
5
6
7
5
10
6
4
9
3
12
5
5
9
9
6
6
6
10
8
6
10
9
7
9
18
6
17
5
6
9
9
3
12
2
8
4
9
7
9
7
13
6
9
6
5
16
5
10
7
9
5
3
13
18
11
11
10
13
9
6
11
12
6
11
18
4
8
8
6
6
12
11
6
3
7
4
7
9
7
18
12
10
7
6
7
8
8
17
12
5
11
15
3
7
6
11
10
5
12
8
9
8
9
6
10
8
12
3
10
19
8
12
9
10
9
6
10
5
7
10
8
4
16
7
10
9
10
7
6
6
15
9
12
1
3
4
6
9
4
6
7
4
7
17
7
8
8
11
9
4
5
7
5
8
6
3
8
10
11
9
8
16
6
14
3
18
9
7
12
11
8
19
15
11
4
8
9
17
7
12
12
6
8
10
6
10
2
8
11
5
27
5
11
14
5
6
7
4
11
8
11
11
3
3
12
9
14
7
9
12
9
11
13
5
13
8
4
10
7
4
7
6
6
4
16
12
6
9
8
4
7
11
4
9
7
12
9
10
9
11
9
4
12
5
11
11
11
5
11
20
16
7
12
7
4
10
25
7
6
16
7
12
9
5
9
3
5
16
3
9
7
4
13
3
16
4
9
3
9
9
9
8
12
7
12
13
15
7
9
7
5
8
5
3
11
3
6
11
7
4
15
15
8
16
3
11
4
10
11
8
15
10
12
5
12
4
7
8
8
8
13
12
8
1
7
18
6
6
7
9
10
9
11
10
6
8
9
10
4
5
8
9
9
1
5
13
5
6
11
8
2
10
8
11
9
12
9
11
14
3
25
7
6
5
6
6
7
1
8
1
7
8
5
10
17
9
7
13
12
9
11
8
5
5
12
8
8
6
8
21
14
13
9
7
14
6
9
8
7
12
14
1
12
10
19
10
10
13
4
6
8
4
14
7
5
18
4
4
8
6
6
8
13
5
18
25
6
3
8
16
7
18
10
17
13
7
10
10
12
13
9
3
11
13
15
5
3
6
5
7
7
1
2
7
7
4
15
14
13
11
8
11
21
5
2
1
14
7
14
7
8
7
9
15
1
9
10
10
15
5
12
11
9
16
10
9
6
9
4
10
8
10
10
8
4
6
6
5
19
11
13
9
5
2
12
7
11
6
8
5
10
11
8
3
9
14
4
6
5
7
2
7
8
5
8
5
9
9
6
9
5
8
6
6
9
8
6
5
5
8
14
15
6
7
21
14
10
6
1
18
10
7
5
7
11
5
7
12
19
1
11
12
8
8
9
5
11
2
6
11
12
15
10
10
7
12
7
11
14
16
9
10
18
15
8
8
6
5
14
9
8
11
6
8
5
5
4
5
11
12
17
5
6
8
7
7
9
4
7
8
7
5
5
12
13
8
5
14
7
8
8
11
7
5
18
8
9
10
10
10
7
15
5
6
1
4
8
6
4
11
8
5
13
7
10
9
2
6
8
11
15
8
8
9
7
9
10
9
17
7
6
4
11
12
4
5
4
12
10
15
13
15
10
17
9
7
10
5
6
8
10
8
7
10
12
3
8
12
6
10
5
17
8
8
8
7
8
12
13
15
10
9
6
8
14
7
11
4
16
4
5
4
9
4
2
8
10
6
8
6
16
6
3
13
1
7
8
7
20
9
18
8
8
12
6
3
3
13
5
8
9
9
7
5
3
7
4
9
12
5
11
8
12
6
13
5
7
11
4
4
6
9
8
9
11
6
4
5
13
13
8
6
3
11
10
8
13
9
8
8
6
13
15
10
3
14
4
9
9
6
5
5
8
7
3
7
9
11
13
8
4
7
11
4
5
14
13
5
9
3
11
8
12
12
7
6
8
16
14
14
8
10
8
3
7
9
9
7
15
11
6
11
9
14
6
11
10
3
8
10
8
9
11
4
12
10
2
20
7
14
7
12
10
33
9
9
3
10
17
6
15
8
11
8
15
3
10
11
5
9
11
12
9
16
6
5
10
4
1
12
5
5
4
9
5
6
9
9
6
8
13
9
7
17
13
19
16
13
9
6
6
5
8
6
8
8
10
4
4
6
3
1
17
5
8
8
5
9
12
12
6
7
5
10
12
5
14
5
10
8
6
11
10
4
15
9
12
6
7
6
6
9
10
11
7
5
9
11
8
10
15
9
6
8
11
6
15
8
6
6
11
5
6
12
9
12
10
6
4
4
7
16
5
3
10
11
7
5
9
8
11
7
4
9
13
10
9
9
6
7
7
18
11
6
3
12
11
7
7
5
4
7
11
15
6
11
4
5
9
7
7
15
7
9
10
13
9
8
4
7
7
8
8
13
8
8
4
8
15
4
6
5
4
9
9
9
10
7
12
9
6
15
8
11
8
9
9
10
9
8
6
11
14
16
5
2
11
6
12
18
11
10
8
21
10
16
6
7
9
11
5
4
8
5
8
10
9
5
9
13
4
10
7
20
9
7
9
7
21
5
17
7
7
8
7
16
8
8
6
7
10
12
9
12
16
5
4
11
19
6
13
10
5
11
12
14
6
4
13
5
5
9
12
9
13
7
2
6
5
10
6
9
5
3
5
1
9
17
15
10
10
9
12
6
10
6
4
6
11
7
11
5
5
4
6
12
13
26
7
15
12
8
14
8
13
7
13
8
11
12
5
16
8
20
7
13
17
9
13
10
11
10
15
7
8
5
6
6
9
8
10
5
10
9
5
6
3
9
10
6
6
2
16
8
11
8
7
5
4
10
7
9
12
9
9
8
9
4
17
10
9
9
5
10
16
4
6
10
5
6
6
10
8
5
6
5
6
6
6
13
5
8
8
5
7
5
17
17
8
8

,page,pre_rev,post_rev,pre_loss,post_loss,post_txt,diffs,pre_txt,category,pre_romanji,...,gpt35_incorrectstrings_time,opennmt_model_textsim,gpt_35_romanji_textsim,gpt35_incorrectstrings_textsim,opennmt_model_simhash_textsim,gpt35_romanji_simhash_textsim,gpt35_incorrectstrings_simhash_textsim,pesedo_romanji,noise_num,pesedo_details
0,881,5958209,9736989,251.51,245.60,1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,"[{'pre': 'を', 'post': 'の'}]",1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,substitution,1987 nen ni kyokubu ginga gun ( dai mazeran ku...,...,0.066108,0.983143,0,0.983143,0.875000,0,0.875000,0,0,"[{'origin_token': 'wo', 'noise_token': 'no', '..."
1,887,31045825,31065369,189.78,175.93,制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,"[{'pre': 'か', 'post': 'も'}]",制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,substitution,"seiyaku ga ooku, dokusenteki ・ chouki ni rensa...",...,0.011402,0.982616,0,0.982616,0.892308,0,0.876923,0,0,"[{'origin_token': 'ka', 'noise_token': 'mo', '..."
2,1253,38176846,38227527,201.24,189.63,一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えられた集団...,"[{'pre': 'れれ', 'post': 'られ'}]",一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えれれた集団...,substitution,issetsu niha gurongi ni yabure ta hokano buzok...,...,0.011292,0.983214,0,0.983214,0.892308,0,0.892308,0,0,"[{'origin_token': 'rere', 'noise_token': 'rare..."
3,1253,35848754,35899590,98.14,94.01,フロント部に金色のプレートなど、随所に金色の装甲が発生している。,"[{'pre': 'に', 'post': 'の'}]",フロント部に金色のプレートなど、随所に金色に装甲が発生している。,substitution,"furonto bu ni kin'iro no pureeto nado, zuisho ...",...,0.009064,0.975900,0,0.975900,0.772727,0,0.772727,0,0,"[{'origin_token': 'ni', 'noise_token': 'no', '..."
4,1432,67727119,68197779,528.34,521.10,このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,"[{'pre': 'もと', 'post': 'もの'}]",このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,substitution,"konoyouna giron wo tsuuji, sukunakutomo roushi...",...,0.013184,0.997275,0,0.997275,0.909091,0,0.909091,0,0,"[{'origin_token': 'moto', 'noise_token': 'mono..."

In [172]:
def textsim_gpt35_pycorrector(df):
    for i in range(df.shape[0]):
        if df.gpt35_incorrectstrings_gen.iloc[i]!="0":
            if type(df.gpt35_incorrectstrings_gen.iloc[i]) == int:
                df.gpt35_incorrectstrings_gen.iloc[i]=  str(df.gpt35_incorrectstrings_gen.iloc[i])
       
            gen_text=''.join(filter(lambda x: x not in punctuation, df.gpt35_incorrectstrings_gen.iloc[i])) 
            org_text=''.join(filter(lambda x: x not in punctuation, df.post_txt.iloc[i]))
            if gen_text == org_text:
                df.gpt35_incorrectstrings_simhash_textsim.iloc[i]=1
                df.gpt35_incorrectstrings_textsim.iloc[i]=1

            else:

                df.gpt35_incorrectstrings_simhash_textsim.iloc[i]=simhash_demo(gen_text,org_text)

                df.gpt35_incorrectstrings_textsim.iloc[i]=tfidf_similarity(gen_text,org_text)

    return df

In [173]:
df=textsim_gpt35_pycorrector(df)
df.head()

11
12
15
0
19
15
4
4
0
10
9
12
7
14
15
6
2
21
18
11
12
10
8
12
7
11
6
7
7
9
10
11
9
13
16
13
11
15
4
9
6
8
9
13
8
7
6
15
8
13
15
6
4
13
13
11
12
6
0
0
8
0
12
4
16
10
13
12
4
11
6
6
2
13
6
13
7
3
6
6
0
9
6
0
7
12
12
13
13
13
13
11
14
6
8
5
10
5
5
6
7
1
8
6
7
0
8
20
13
12
4
4
9
4
14
0
12
8
6
8
5
17
6
6
8
1
4
19
5
5
9
11
10
11
0
5
0
10
4
8
9
8
7
10
4
9
13
15
7
11
10
4
7
9
5
8
8
8
10
0
0
3
1
0
6
11
4
10
0
9
11
12
9
4
10
8
16
11
10
6
14
5
10
13
7
7
8
11
0
9
0
0
14
17
9
11
12
5
0
10
11
0
9
6
17
11
10
6
6
15
3
15
17
15
5
16
1
6
5
15
5
11
4
9
31
4
8
12
9
4
7
6
7
0
2
15
13
5
14
5
7
8
0
6
8
10
6
0
9
17
0
9
11
14
9
9
17
11
7
14
0
8
0
12
4
1
0
16
12
13
13
7
11
11
9
6
5
10
13
6
6
9
15
11
5
17
4
7
7
10
6
11
6
16
8
9
10
9
14
10
11
2
6
5
0
9
9
17
13
7
10
8
5
10
18
15
4
19
0
12
0
6
4
11
12
9
16
13
11
6
9
5
0
0
10
8
5
6
6
8
15
2
7
5
11
8
12
10
6
8
7
0
13
5
11
11
10
8
5
14
5
9
10
7
11
7
8
9
0
12
11
10
0
10
8
7
10
8
0
12
14
6
8
9
0
10
0
9
0
15
8
3
10
7
11
15
8
15
14
4
15
11
14
2
6
0
12
6
9
5
20
13
4
6
0
0
0
15
5
13
15
16
5
0
8
13
9
1
10
6
8
12
2
12
4
11
23
9
0
6
10
3
9
7
13
8
8
4
9
6
0
11
22
5
7
28
11
10
9
9
8
5
7
6
11
0
13
13
18
8
10
9
10
15
0
11
11
13
12
5
14
16
13
13
13
0
14
13
9
9
7
0
17
2
3
8
4
11
16
7
14
0
12
17
13
9
14
9
8
6
6
3
5
0
6
0
7
14
7
21
3
5
3
5
12
8
6
3
17
5
7
0
0
7
5
21
13
7
19
10
9
13
7
0
0
0
7
10
6
7
15
5
7
6
5
8
1
21
13
35
0
12
8
9
12
15
6
8
9
3
9
11
20
14
8
6
6
0
0
3
9
6
9
9
8
0
4
9
8
14
8
8
8
12
12
2
13
5
13
11
8
7
11
10
4
12
6
9
3
4
6
19
9
8
6
7
7
6
6
13
6
6
16
5
5
8
12
0
6
11
8
0
5
9
11
4
9
21
4
8
19
9
9
4
15
7
5
5
7
10
0
18
15
10
12
11
16
18
7
5
10
23
13
4
5
10
14
6
4
6
6
10
8
10
12
6
6
0
0
13
12
11
17
15
13
12
7
4
9
3
13
10
12
22
15
6
8
6
12
7
6
9
8
0
10
6
13
5
14
7
12
6
10
7
4
5
12
13
6
4
4
7
12
7
0
14
9
11
7
7
7
4
0
7
15
2
11
14
15
10
12
10
7
16
7
6
5
6
12
0
9
8
0
10
7
16
9
6
10
11
0
10
18
13
18
9
11
6
16
8
3
3
10
6
7
18
14
10
7
18
9
9
17
4
17
8
8
6
4
11
16
5
0
12
16
8
13
7
3
9
15
10
19
15
13
0
14
19
5
11
8
7
16
15
9
17
4
11
15
9
11
4
12
2
12
4
0
12
9
18
0
5
13
8
11
0
2
20
13
7
7
4
11
3
16
5
0
0
13
5
6
14
6
5
14
11
4
1
10
8
7
11
8
11
4
12
0
12
6
20
12
11
23
0
9
7
12
8
17
8
12
15
12
11
11
10
10
20
0
8
9
0
15
6
3
0
4
11
3
10
6
13
12
5
2
8
8
14
11
8
7
3
13
8
10
10
14
13
7
6
12
6
15
13
9
10
7
5
10
13
7
4
7
8
10
10
0
9
7
6
13
11
16
11
13
9
18
5
5
0
7
9
11
13
1
6
11
0
6
5
0
8
9
5
10
11
10
5
0
6
2
17
0
6
11
6
11
7
9
13
13
0
8
13
9
14
13
19
6
12
12
9
10
7
9
11
7
6
9
2
10
7
2
6
5
7
10
9
13
13
0
8
8
20
4
13
7
7
2
6
9
12
6
5
11
6
11
9
6
14
16
12
7
6
2
5
6
4
7
12
4
15
13
5
10
10
9
4
5
6
5
6
17
16
8
2
9
12
2
9
9
8
9
14
0
7
8
13
4
24
14
7
6
13
3
15
9
10
8
11
12
13
3
10
22
8
6
8
13
8
7
9
18
6
11
15
6
9
4
12
13
22
11
8
9
7
2
9
5
3
4
20
7
7
5
7
10
13
5
17
13
8
2
4
7
7
3
7
4
28
6
24
8
0
12
14
7
13
5
6
13
14
8
8
0
15
13
8
5
11
8
6
3
8
4
11
8
3
14
10
6
7
12
9
7
8
13
5
16
8
5
14
14
7
9
12
2
9
8
5
14
19
9
9
11
15
15
8
15
10
8
3
4
7
11
11
3
15
7
4
14
8
17
6
18
7
12
3
7
21
13
5
9
9
9
4
9
6
18
6
8
6
10
5
14
9
6
8
6
22
11
0
18
13
28
6
5
12
17
4
14
8
14
4
7
9
10
12
20
9
4
17
8
7
14
9
7
19
13
6
10
2
8
22
8
11
9
7
3
9
6
15
15
6
9
13
5
8
5
13
17
11
5
5
12
9
9
4
4
8
10
8
4
16
4
4
6
5
12
6
17
4
16
5
14
10
0
10
6
7
8
9
16
7
0
11
11
12
5
6
5
8
12
0
7
5
4
5
10
10
6
8
4
10
3
7
14
9
9
8
15
10
13
14
19
4
8
8
5
10
9
5
16
7
8
12
21
10
5
4
6
4
5
2
5
9
16
21
2
6
9
9
5
8
11
22
19
8
6
15
4
10
8
12
10
9
14
14
5
16
6
11
15
31
12
5
11
9
9
4
8
9
11
14
7
14
6
5
7
18
6
13
11
6
6
13
10
11
0
13
10
10
5
18
9
6
9
10
12
12
12
13
10
10
6
7
11
5
8
19
21
7
7
2
5
8
6
12
15
12
27
17
12
9
10
10
2
4
9
8
4
10
14
7
5
7
14
11
6
14
13
8
9
5
10
21
7
12
9
11
14
4
23
11
6
28
24
9
0
10
7
15
6
9
11
8
7
6
5
11
9
11
10
5
2
4
3
14
12
6
23
20
8
9
6
9
6
14
14
4
12
8
11
9
7
18
12
8
6
7
12
7
10
18
12
11
10
14
7
6
7
12
11
10
14
9
8
6
8
4
6
17
17
11
6
12
14
5
12
6
7
12
7
0
14
0
13
7
5
20
9
5
8
13
9
12
8
12
5
5
14
10
5
7
6
8
6
17
8
11
6
11
13
6
8
5
6
4
10
9
8
1
7
12
12
7
4
7
5
23
10
4
9
23
10
13
8
8
7
8
2
10
27
3
7
6
9
17
16
7
8
11
11
7
3
11
6
10
1
7
7
6
10
6
7
4
6
9
10
11
8
13
11
11
10
9
7
11
8
9
10
16
19
8
10
19
8
13
14
5
13
9
7
8
15
10
7
6
15
9
10
2
4
11
6
9
22
13
14
12
12
10
7
11
8
3
10
12
16
11
6
6
12
11
4
3
8
7
3
4
7
1
9
5
13
10
10
8
11
20
8
4
11
1
10
8
8
6
7
9
12
15
8
17
13
14
6
8
9
16
4
19
8
10
10
13
7
7
9
10
12
16
9
7
6
8
7
17
14
9
3
11
10
13
8
10
2
2
12
15
7
5
9
8
10
0
15
9
6
14
9
10
9
4
7
7
12
9
12
14
13
3
9
6
8
6
5
10
13
9
12
10
5
8
13
6
4
7
7
7
8
13
10
4
11
9
1
14
6
11
3
0
4
6
8
20
12
15
24
15
13
7
13
6
5
7
6
5
26
24
20
6
6
5
8
10
3
8
12
14
5
9
23
9
17
13
9
12
2
12
8
7
4
11
8
6
7
6
5
14
11
13
7
20
15
15
2
7
8
15
10
4
15
0
7
7
11
10
13
5
13
30
3
14
10
12
6
9
7
2
4
18
7
12
7
12
8
18
14
9
9
12
8
8
6
7
6
10
10
10
19
10
7
14
9
12
4
7
8
15
7
12
22
7
18
0
9
19
9
19
17
13
3
12
19
4
5
11
7
12
8
9
4
9
6
7
13
10
8
16
15
8
18
0
7
10
12
7
0
16
15
7
10
9
2
13
5
5
12
9
8
8
23
10
5
7
5
0
6
5
17
11
12
14
12
2
8
8
7
6
16
5

,page,pre_rev,post_rev,pre_loss,post_loss,post_txt,diffs,pre_txt,category,pre_romanji,...,gpt35_incorrectstrings_time,opennmt_model_textsim,gpt_35_romanji_textsim,gpt35_incorrectstrings_textsim,opennmt_model_simhash_textsim,gpt35_romanji_simhash_textsim,gpt35_incorrectstrings_simhash_textsim,pesedo_romanji,noise_num,pesedo_details
0,881,5958209,9736989,251.51,245.60,1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,"[{'pre': 'を', 'post': 'の'}]",1987年に局部銀河群（大マゼラン雲）内において超新星爆発(SN1987A)が起こったため、...,substitution,1987 nen ni kyokubu ginga gun ( dai mazeran ku...,...,0.066108,0.983143,0,1.000000,0.875000,0,1.000000,0,0,"[{'origin_token': 'wo', 'noise_token': 'no', '..."
1,887,31045825,31065369,189.78,175.93,制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,"[{'pre': 'か', 'post': 'も'}]",制約が多く、独占的・長期に連載されるため（作者の死によって連載終了となることも多い）マンネリ...,substitution,"seiyaku ga ooku, dokusenteki ・ chouki ni rensa...",...,0.011402,0.982616,0,0.988372,0.892308,0,0.830769,0,0,"[{'origin_token': 'ka', 'noise_token': 'mo', '..."
2,1253,38176846,38227527,201.24,189.63,一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えられた集団...,"[{'pre': 'れれ', 'post': 'られ'}]",一説にはグロンギに敗れた他の部族が奴隷として無理やりグロンギに改造された傘下に加えれれた集団...,substitution,issetsu niha gurongi ni yabure ta hokano buzok...,...,0.011292,0.983214,0,1.000000,0.892308,0,1.000000,0,0,"[{'origin_token': 'rere', 'noise_token': 'rare..."
3,1253,35848754,35899590,98.14,94.01,フロント部に金色のプレートなど、随所に金色の装甲が発生している。,"[{'pre': 'に', 'post': 'の'}]",フロント部に金色のプレートなど、随所に金色に装甲が発生している。,substitution,"furonto bu ni kin'iro no pureeto nado, zuisho ...",...,0.009064,0.975900,0,1.000000,0.772727,0,1.000000,0,0,"[{'origin_token': 'ni', 'noise_token': 'no', '..."
4,1432,67727119,68197779,528.34,521.10,このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,"[{'pre': 'もと', 'post': 'もの'}]",このような議論を通じ、少なくとも老子なる人物が生きたであろう時代と『老子道徳経』が作られた時...,substitution,"konoyouna giron wo tsuuji, sukunakutomo roushi...",...,0.013184,0.997275,0,1.000000,0.909091,0,1.000000,0,0,"[{'origin_token': 'moto', 'noise_token': 'mono..."

In [141]:
dff=df.copy()

In [174]:
df.to_csv("Japanese_correction_datasets/jwtd/gen/jwtd_test_combined.csv",index=False)

In [178]:
df.category.value_counts()

kanji-conversion    3061
insertion           2127
substitution        1689
deletion            1665
Name: category, dtype: int64